set_property IOSTANDARD LVCMOS33 [get_ports *]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports rst_n]

set_property PACKAGE_PIN R15 [get_ports submit]
set_property PACKAGE_PIN U4 [get_ports oct_up]
set_property PACKAGE_PIN R17 [get_ports oct_down]
set_property PACKAGE_PIN R11 [get_ports cancel]

set_property PACKAGE_PIN R1 [get_ports {note_key[6]}]
set_property PACKAGE_PIN N4 [get_ports {note_key[5]}]
set_property PACKAGE_PIN M4 [get_ports {note_key[4]}]
set_property PACKAGE_PIN R2 [get_ports {note_key[3]}]
set_property PACKAGE_PIN P2 [get_ports {note_key[2]}]
set_property PACKAGE_PIN P3 [get_ports {note_key[1]}]
set_property PACKAGE_PIN P4 [get_ports {note_key[0]}]

set_property PACKAGE_PIN U3 [get_ports is_rw]

set_property PACKAGE_PIN P5 [get_ports reset]

set_property PACKAGE_PIN T5 [get_ports {length_key[6]}]
set_property PACKAGE_PIN T3 [get_ports {length_key[5]}]
set_property PACKAGE_PIN R3 [get_ports {length_key[4]}]
set_property PACKAGE_PIN V4 [get_ports {length_key[3]}]
set_property PACKAGE_PIN V5 [get_ports {length_key[2]}]
set_property PACKAGE_PIN V2 [get_ports {length_key[1]}]
set_property PACKAGE_PIN U2 [get_ports {length_key[0]}]

set_property PACKAGE_PIN K2 [get_ports {led[6]}]
set_property PACKAGE_PIN J2 [get_ports {led[5]}]
set_property PACKAGE_PIN J3 [get_ports {led[4]}]
set_property PACKAGE_PIN H4 [get_ports {led[3]}]
set_property PACKAGE_PIN J4 [get_ports {led[2]}]
set_property PACKAGE_PIN G3 [get_ports {led[1]}]
set_property PACKAGE_PIN G4 [get_ports {led[0]}]

set_property PACKAGE_PIN K3 [get_ports {led_aux[6]}]
set_property PACKAGE_PIN M1 [get_ports {led_aux[5]}]
set_property PACKAGE_PIN L1 [get_ports {led_aux[4]}]
set_property PACKAGE_PIN K6 [get_ports {led_aux[3]}]
set_property PACKAGE_PIN J5 [get_ports {led_aux[2]}]
set_property PACKAGE_PIN H5 [get_ports {led_aux[1]}]
set_property PACKAGE_PIN H6 [get_ports {led_aux[0]}]

set_property PACKAGE_PIN G2 [get_ports {seg_en[0]}]
set_property PACKAGE_PIN C2 [get_ports {seg_en[1]}]
set_property PACKAGE_PIN C1 [get_ports {seg_en[2]}]
set_property PACKAGE_PIN H1 [get_ports {seg_en[3]}]
set_property PACKAGE_PIN G1 [get_ports {seg_en[4]}]
set_property PACKAGE_PIN F1 [get_ports {seg_en[5]}]
set_property PACKAGE_PIN E1 [get_ports {seg_en[6]}]
set_property PACKAGE_PIN G6 [get_ports {seg_en[7]}]

set_property PACKAGE_PIN B4 [get_ports {tube1[7]}]
set_property PACKAGE_PIN A4 [get_ports {tube1[6]}]
set_property PACKAGE_PIN A3 [get_ports {tube1[5]}]
set_property PACKAGE_PIN B1 [get_ports {tube1[4]}]
set_property PACKAGE_PIN A1 [get_ports {tube1[3]}]
set_property PACKAGE_PIN B3 [get_ports {tube1[2]}]
set_property PACKAGE_PIN B2 [get_ports {tube1[1]}]
set_property PACKAGE_PIN D5 [get_ports {tube1[0]}]

set_property PACKAGE_PIN D4 [get_ports {tube2[7]}]
set_property PACKAGE_PIN E3 [get_ports {tube2[6]}]
set_property PACKAGE_PIN D3 [get_ports {tube2[5]}]
set_property PACKAGE_PIN F4 [get_ports {tube2[4]}]
set_property PACKAGE_PIN F3 [get_ports {tube2[3]}]
set_property PACKAGE_PIN E2 [get_ports {tube2[2]}]
set_property PACKAGE_PIN D2 [get_ports {tube2[1]}]
set_property PACKAGE_PIN H2 [get_ports {tube2[0]}]

set_property PACKAGE_PIN H17 [get_ports buzzer]
set_property PACKAGE_PIN T1 [get_ports T1]